### Create a User (POST Request)
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "postman1",
    "email": "postman@gmail.com",
    "role": "postman1_role"
}

### Get User by ID (GET Request)
GET http://localhost:8080/users/1

### Update User (PUT Request)
PUT http://localhost:8080/users/1
Content-Type: application/json

{
    "name": "updatedName",
    "email": "updated@gmail.com",
    "role": "updated_role"
}

### Delete User (DELETE Request)
DELETE http://localhost:8080/users/1
