name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - main


jobs:
  build:
    name: Build Spring Boot App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
            cd org.learning.spring.boot.learning 
            mvn clean install

  test:
    name: Test Stage
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            
      - name: Run Tests
        run: |
            cd org.learning.spring.boot.learning 
            mvn test

  deploy:
    name: Deploy Stage
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to Docker
        run: echo "Deploying to Docker..."